### ISSUE TITLE
Allow exclude from backups

### ISSUE THREAD

**Issue by baurmatt** [syseleven/puppet-restic#8]
Please make it possible to exclude files from the backup -> https://restic.readthedocs.io/en/latest/040_backup.html#excluding-files

`--exclude` should be enough for now :)

**Comment by baurmatt** [comment]
This can be hacked:

```puppet
  concat::fragment { 'restic_fragment_restic_BACKUP_FLAGS_EXCLUDE':
    content => 'BACKUP_FLAGS="--exclude /path/to/be/excluded /path/to/be/backuped"',
    target  => '/etc/default/restic_myapplication',
    order   => '100',
  }
```

**Comment by crazymind1337** [comment]
Won't be fixed. There is the parameter `backup_flags` which can be used for your case.
